#!/usr/bin/env python3
"""Generate docs/pages.md and docs/components.md from the catalogue.

These two files are an inventory, not prose. Hand-writing them would mean
keeping a second copy of facts the seed already holds, and a second copy of
facts drifts - that is the whole reason assets/kit.css is generated rather
than pasted into thirty-four pages. So: one source, regenerated.

    python3 scripts/build_docs.py

Run it after any change to the catalogue. scripts/check_v2_sync.py fails if
these files are stale, the same way it fails on a stale embedded seed.
"""
import json
import re
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SEED = ROOT / "source" / "data-seed.json"
DOCS = ROOT / "docs"

STAMP = ("<!-- GENERATED by scripts/build_docs.py from source/data-seed.json. "
         "Do not edit by hand - your edit will be overwritten. -->")

# The structural primitives worth reporting per screen, in the order they appear
# down the page. Anything not in here is detail inside a section, not structure.
STRUCTURE = [
    ("vp-pagebar",       "page header"),
    ("vp-tabs",          "tab strip"),
    ("vp-subtabbar",     "sub-tab bar"),
    ("vp-statbar",       "stat summary bar"),
    ("vp-panel",         "section (white panel)"),
    ("vp-maparea",       "map work area (gutter exemption)"),
    ("vp-dcc-sec",       "capacity card"),
    ("vp-gdd-card",      "metric card"),
    ("vp-dcc-actionbar", "sticky action bar"),
]


def count(code, cls):
    return len(re.findall(r'class="%s[ "]' % re.escape(cls), code))


def headings(code):
    out = []
    for lvl, raw in re.findall(r"<h([1-6])[^>]*>(.*?)</h\1>", code, re.S):
        text = re.sub(r"<[^>]+>", "", raw)
        text = re.sub(r"\s+", " ", text).strip()
        if text:
            out.append((int(lvl), text))
    return out


def pages_md(seed):
    flows = {f["id"]: f for f in seed["flows"]}
    by_flow = defaultdict(list)
    for s in seed["screens"]:
        by_flow[s["flowId"]].append(s)

    L = [STAMP, "", "# Pages built so far", "",
         "Every screen in the catalogue: what it is *for* first, then what it is *made of*. "
         "Read the UX to decide whether something belongs; read the structure to build it.", "",
         "## The belonging test", "",
         "> Something belongs on a page when it serves that page's **decision**. If it serves "
         "a different decision, it belongs on the page that owns that decision - or on a new "
         "one.", "",
         "Then check the two lists:", "",
         "- already in **answers** -> it exists; extend it rather than adding beside it",
         "- listed under **not here** -> it was considered and rejected; read why before "
         "re-proposing it",
         "- in neither -> genuinely new, and the decision above is the test", "",
         "**answers and not here are scoped to one screen, never to the module.** "
         "\"DC Capacity does not show per-pilot detail\" excludes it from *that screen*. "
         "A second screen in the same module - a tab - is a different screen, and the "
         "exclusion does not reach it. Reading a screen's exclusions as the module's is "
         "how a tab stops being considered.", "",
         "Once the page is settled, [section-rules.md](section-rules.md) decides whether it "
         "is a new section or baked into an existing one.", "",
         "%d modules, %d screens, %d components."
         % (len(seed["flows"]), len(seed["screens"]), len(seed["components"])), "",
         "---", ""]

    for fid in sorted(flows, key=lambda i: flows[i].get("order", 0)):
        f = flows[fid]
        screens = sorted(by_flow[fid], key=lambda s: (s.get("version", "live"), s.get("order", 0)))
        L += ["## %s" % f["name"], "", "`%s` - %d screen%s" % (fid, len(screens), "" if len(screens) == 1 else "s"), ""]
        if f.get("description"):
            L += ["%s" % f["description"], ""]
        ux = f.get("ux") or {}
        for key, label in (("who", "Who"), ("cadence", "How often"), ("journey", "Journey")):
            if ux.get(key):
                L += ["**%s** — %s" % (label, ux[key]), ""]
        L += (["> **<Yash will add more>**", ""] if ux
              else ["> *UX context not written yet.*", ""])

        for s in screens:
            ver = s.get("version", "live")
            L += ["### %s" % s["name"], "",
                  "`%s`%s" % (s["id"], "  ·  **%s** version" % ver if ver != "live" else ""), ""]
            ux = s.get("ux") or {}
            if ux.get("job"):
                L += ["**Job** — %s" % ux["job"], ""]
            if ux.get("decision"):
                L += ["**Decision it supports** — %s" % ux["decision"], ""]
            if ux.get("answers"):
                L += ["**Answers today**", ""] + ["- %s" % a for a in ux["answers"]] + [""]
            if ux.get("notHere"):
                L += ["**Deliberately not here**", ""] + ["- %s" % n for n in ux["notHere"]] + [""]
            L += (["> **<Yash will add more>**", ""] if ux
                  else ["> *UX context not written yet — only structure is known for this screen.*", ""])

            if s.get("description"):
                L += ["**Structure in words** — %s" % s["description"], ""]

            struct = [(label, count(s["code"], cls)) for cls, label in STRUCTURE]
            struct = [(l, n) for l, n in struct if n]
            if struct:
                L += ["**Structure** - " + ", ".join(
                    "%s%s" % (l, "" if n == 1 else " ×%d" % n) for l, n in struct), ""]

            hs = [(l, t) for l, t in headings(s["code"]) if l <= 4]
            if hs:
                L += ["**Headings** - " + ", ".join("`h%d` %s" % (l, t) for l, t in hs), ""]

            if s.get("states"):
                L += ["**States** - " + ", ".join(s["states"]), ""]
            if s.get("components"):
                L += ["**Components** - " + ", ".join("`%s`" % c for c in s["components"]), ""]
        L += ["---", ""]
    return "\n".join(L).rstrip() + "\n"


def components_md(seed):
    used = defaultdict(list)
    for s in seed["screens"]:
        for c in s.get("components", []):
            used[c].append(s["id"])

    by_cat = defaultdict(list)
    for c in seed["components"]:
        by_cat[c.get("category", "Uncategorised")].append(c)

    orphans = [c["id"] for c in seed["components"] if not used.get(c["id"])]

    L = [STAMP, "", "# Component inventory", "",
         "Every component in the library, what it is, its sizing rule, and which screens "
         "render it. Check here before inventing something - if a pattern is already "
         "here, use it; if it is not, that is a grey box and a new component.", "",
         "%d components across %d categories." % (len(seed["components"]), len(by_cat)), ""]

    if orphans:
        L += ["> **%d not rendered by any screen:** %s. Catalogued for reuse, with no "
              "page depending on them yet." % (len(orphans), ", ".join("`%s`" % o for o in orphans)), ""]
    L += ["---", ""]

    for cat in sorted(by_cat):
        L += ["## %s" % cat, "",
              "| component | what it is | sizing | used on |", "|---|---|---|---|"]
        for c in sorted(by_cat[cat], key=lambda x: x.get("order", 0)):
            where = used.get(c["id"]) or []
            L.append("| `%s` | %s | %s | %s |" % (
                c["id"],
                (c.get("description") or "-").replace("|", "\\|"),
                (c.get("sizing") or "-").replace("|", "\\|"),
                ", ".join("`%s`" % w for w in where) if where else "*not yet used*"))
        L.append("")
    return "\n".join(L).rstrip() + "\n"


def main():
    check = "--check" in sys.argv
    seed = json.loads(SEED.read_text(encoding="utf-8"))
    DOCS.mkdir(exist_ok=True)
    stale = []
    for name, body in (("pages.md", pages_md(seed)), ("components.md", components_md(seed))):
        path = DOCS / name
        if check:
            if not path.exists() or path.read_text(encoding="utf-8") != body:
                stale.append("docs/" + name)
        else:
            path.write_text(body, encoding="utf-8")
    if check:
        if stale:
            sys.exit("stale: %s - run python3 scripts/build_docs.py" % ", ".join(stale))
        print("docs/pages.md and docs/components.md are current.")
    else:
        print("Wrote docs/pages.md and docs/components.md from %d screens, %d components."
              % (len(seed["screens"]), len(seed["components"])))


if __name__ == "__main__":
    main()
